import {
  CardColor,
  CardRarity,
  CardType,
  type Card,
  type CardId,
} from './cardTypes.ts'

export const sampleCards: readonly Card[] = [
  {
    id: 'OP01-001',
    code: 'OP01-001',
    name: 'Harbor Captain',
    type: CardType.Leader,
    colors: [CardColor.Red],
    rarity: CardRarity.Leader,
    life: 5,
    power: 5000,
    text: 'Placeholder leader card for parser and validator tests.',
    tags: ['leader', 'starter'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-002',
    code: 'OP01-002',
    name: 'Tidal Strategist',
    type: CardType.Leader,
    colors: [CardColor.Blue],
    rarity: CardRarity.Leader,
    life: 5,
    power: 5000,
    text: 'Second placeholder leader for validation edge cases.',
    tags: ['leader', 'control'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-101',
    code: 'OP01-101',
    name: 'Deck Lookout',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 1,
    power: 2000,
    counter: 1000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-102',
    code: 'OP01-102',
    name: 'Anchor Brawler',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 2,
    power: 3000,
    counter: 1000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-103',
    code: 'OP01-103',
    name: 'Boiler Runner',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Uncommon,
    cost: 2,
    power: 4000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-104',
    code: 'OP01-104',
    name: 'Signal Drummer',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Uncommon,
    cost: 3,
    power: 5000,
    counter: 1000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-105',
    code: 'OP01-105',
    name: 'Cannon Rigger',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 3,
    power: 4000,
    counter: 2000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-106',
    code: 'OP01-106',
    name: 'Quartermaster',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Rare,
    cost: 4,
    power: 6000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-107',
    code: 'OP01-107',
    name: 'Line Breaker',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 1,
    power: 1000,
    counter: 2000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-108',
    code: 'OP01-108',
    name: 'Firewatch Mate',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Uncommon,
    cost: 5,
    power: 7000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-109',
    code: 'OP01-109',
    name: 'Cargo Defender',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 2,
    power: 3000,
    counter: 1000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-110',
    code: 'OP01-110',
    name: 'Signal Flare',
    type: CardType.Event,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 1,
    text: 'Placeholder event card.',
    tags: ['red', 'event'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-111',
    code: 'OP01-111',
    name: 'Deckside Charge',
    type: CardType.Event,
    colors: [CardColor.Red],
    rarity: CardRarity.Uncommon,
    cost: 2,
    text: 'Placeholder event card.',
    tags: ['red', 'event'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-112',
    code: 'OP01-112',
    name: 'Training Yard',
    type: CardType.Stage,
    colors: [CardColor.Red],
    rarity: CardRarity.Rare,
    cost: 2,
    text: 'Placeholder stage card.',
    tags: ['red', 'stage'],
    isPlaceholder: true,
  },
  {
    id: 'OP01-113',
    code: 'OP01-113',
    name: 'Breakwater Guard',
    type: CardType.Character,
    colors: [CardColor.Red],
    rarity: CardRarity.Common,
    cost: 4,
    power: 5000,
    tags: ['red', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP02-101',
    code: 'OP02-101',
    name: 'Mist Navigator',
    type: CardType.Character,
    colors: [CardColor.Blue],
    rarity: CardRarity.Common,
    cost: 2,
    power: 3000,
    counter: 1000,
    tags: ['blue', 'character'],
    isPlaceholder: true,
  },
  {
    id: 'OP02-102',
    code: 'OP02-102',
    name: 'Wave Ledger',
    type: CardType.Event,
    colors: [CardColor.Blue],
    rarity: CardRarity.Uncommon,
    cost: 3,
    text: 'Placeholder blue event card.',
    tags: ['blue', 'event'],
    isPlaceholder: true,
  },
]

export const sampleCardsById: Readonly<Record<CardId, Card>> = sampleCards.reduce<
  Record<CardId, Card>
>((lookup, card) => {
  lookup[card.id] = card
  return lookup
}, {})
